### ISSUE TITLE
Heroku ban

### ISSUE THREAD

**Issue by lonelynek0** [itsZECHS/TorrentiumAPI#9]
Heroku bans the app after few minutes, making it the app useless on that platform.
Is there a way to host it on alternative service? Or on a cloud VPS like Oracle Cloud?

**Comment by itsZECHS** [comment]
> Heroku bans the app after few minutes

Interesting, I have been using this for about 15 months now.
Is your account verified? If not that's most likely the culprit.

> host it on alternative service?

Yes! absolutely. It's just a  docker app at the end of the day.

**Comment by lonelynek0** [comment]
> Is your account verified? If not that's most likely the culprit.

if you mean using a credit card, sadly no.
but i loved the idea of app!

**Comment by itsZECHS** [comment]
> if you mean using a credit card, sadly no.

Well mine is verified, and hasn't been banned yet

> but i loved the idea of app!

Check out the [dev branch](https://github.com/itsZECHS/TorrentiumAPI/tree/development), been adding some new stuff, next update is going to be great!

**Comment by lonelynek0** [comment]
> Check out the [dev branch](https://github.com/itsZECHS/TorrentiumAPI/tree/development), been adding some new stuff, next update is going to be great!

will do. thanks for the answers.
